### PR TITLE
Deleting custom-search-mode package

### PR DESCRIPTION
**Pull request by kbielikova**

### CODE REVIEW

**Comment by cgillis-aras** [comment]
The _package.config_ is hard-coded in terms of how it installs each individual project, and it still contains a reference to Custom Search Mode. Could you remove the reference there as well?

**Comment by kbielikova** [comment]
@cgillis-aras sure, thank you, done

**Comment by cgillis-aras** [comment]
I installed it and it all looks good. One more quick thing and it should be good to go. Could you change the _<version/>_ and _<version_label/>_ tags in the package.config to indicate that it's for 12.0 SP15?

**Comment by kbielikova** [comment]
@cgillis-aras also done

**Pull request merged**
